#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const configPath = process.env.LOGSAFE_CONFIG ?? path.join(root, 'logsafe.config.json')
const outPath = process.env.LOGSAFE_UI_OUT ?? path.join(root, 'ui', 'src', 'plugins.generated.ts')

function readConfig() {
  if (!fs.existsSync(configPath)) return []
  try {
    const parsed = JSON.parse(fs.readFileSync(configPath, 'utf8'))
    return Array.isArray(parsed.plugins) ? parsed.plugins.filter((p) => typeof p === 'string') : []
  } catch { return [] }
}

const require = createRequire(path.join(root, 'noop.js'))
const entries = []
for (const spec of readConfig()) {
  let pkg
  try { pkg = require(`${spec}/package.json`) } catch { console.warn(`[plugins-sync] cannot resolve ${spec}; skipping`); continue }
  const m = pkg.logsafe
  if (!m?.id || !m.ui) continue // ui-only relevance: no ui entry → nothing to import
  entries.push({ id: m.id, priority: m.priority ?? 0, spec })
}
entries.sort((a, b) => b.priority - a.priority)

const imports = entries.map((e, i) => `import p${i} from '${e.spec}/ui'`).join('\n')
const list = entries.map((_, i) => `p${i}`).join(', ')

const lines = [
  '// AUTO-GENERATED by scripts/plugins-sync.mjs — do not edit by hand.',
  `import type { UIPlugin } from '@coglet/logsafe-plugin-sdk/ui'`,
]
if (imports) lines.push(imports)
lines.push(`export const uiPlugins: UIPlugin[] = [${list}]`)
const body = lines.join('\n') + '\n'

fs.writeFileSync(outPath, body)
console.log(`[plugins-sync] wrote ${entries.length} plugin(s) to ${path.relative(root, outPath)}`)
